FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    nfs-common \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /nfs

WORKDIR /app

COPY requirements1.txt .
RUN pip install -r requirements1.txt

COPY main.py .
COPY data-gen.py .
COPY tests ./tests
COPY data/demo.db /nfs/demo.db

EXPOSE 5000

CMD ["python3", "main.py"]

